/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RaindropToObsidian
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");
var import_obsidian4 = require("obsidian");

// src/utils/fileUtils.ts
async function doesPathExist(app, path) {
  return app.vault.adapter.exists(path);
}
async function isPathAFolder(app, path) {
  const stat = await app.vault.adapter.stat(path);
  return (stat == null ? void 0 : stat.type) === "folder";
}
async function createFolder(app, path) {
  const doesFolderExist = await doesPathExist(app, path);
  if (doesFolderExist) {
    const isFolder = await isPathAFolder(app, path);
    if (isFolder) return true;
    throw new Error(`Path exists but is not a folder: ${path}`);
  }
  try {
    await app.vault.createFolder(path);
    return true;
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to create folder at ${path}: ${errorMessage}`);
  }
}
function sanitizeFileName(fileName) {
  const invalidChars = /[/\\:*?"<>|#%&{}$!@'`+=]/g;
  const replacement = "";
  const isStringEmpty = !fileName || fileName.trim() === "";
  if (isStringEmpty) return "Unnamed_Raindrop";
  const sanitizedName = fileName.replace(invalidChars, replacement).trim();
  const isSanitizedEmpty = !sanitizedName;
  const maxLength = 200;
  return (isSanitizedEmpty ? "Unnamed_Raindrop" : sanitizedName).substring(0, maxLength);
}
async function createFolderStructure(app, fullPath) {
  if (!fullPath || fullPath === "/") return true;
  try {
    const doesExist = await doesPathExist(app, fullPath);
    if (doesExist) {
      const isFolder = await isPathAFolder(app, fullPath);
      if (isFolder) return true;
      throw new Error(`Path exists but is not a folder: ${fullPath}`);
    }
    const lastSlashIndex = fullPath.lastIndexOf("/");
    if (lastSlashIndex > 0) {
      const parentPath = fullPath.substring(0, lastSlashIndex);
      await createFolderStructure(app, parentPath);
    }
    await createFolder(app, fullPath);
    return true;
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to create/verify folder: ${fullPath}. Error: ${errorMessage}.`);
  }
}

// src/utils/apiUtils.ts
var import_obsidian = require("obsidian");
function createRateLimiter(maxRequestsPerMinute = 60, delayBetweenRequests = 300) {
  let requestCount = 0;
  let resetTime = Date.now() + 6e4;
  const checkLimit = async () => {
    const now = Date.now();
    if (now > resetTime) {
      resetTime = now + 6e4;
      requestCount = 0;
    }
    if (requestCount >= maxRequestsPerMinute) {
      const waitTime = resetTime - now;
      console.log(`Rate limit reached. Waiting ${waitTime}ms before next request.`);
      await new Promise((resolve) => setTimeout(resolve, waitTime));
      resetTime = Date.now() + 6e4;
      requestCount = 0;
    } else {
      await new Promise((resolve) => setTimeout(resolve, delayBetweenRequests));
    }
    requestCount++;
  };
  const resetCounter = () => {
    resetTime = Date.now() + 6e4;
    requestCount = 0;
    console.log("Rate limiter counter reset.");
  };
  return { checkLimit, resetCounter };
}
function parseApiResponse(response) {
  if (typeof response === "string") {
    return JSON.parse(response);
  }
  return response;
}
async function handleRequestError(error, rateLimiter, attemptNumber, maxRetries, delayBetweenRetries) {
  const isLastAttempt = attemptNumber >= maxRetries - 1;
  if (error.status === 429 || error.message && error.message.includes("rate limit")) {
    console.log("Rate limit hit, resetting counter and waiting...");
    rateLimiter.resetCounter();
    await new Promise((resolve) => setTimeout(resolve, delayBetweenRetries * 2));
    return true;
  }
  console.error(`Error in API request (attempt ${attemptNumber + 1}/${maxRetries}):`, error);
  if (!isLastAttempt) {
    await new Promise((resolve) => setTimeout(resolve, delayBetweenRetries));
    return true;
  }
  return false;
}
async function fetchWithRetry(appOrUrl, urlOrOptions, optionsOrRateLimiter, rateLimiterOrMaxRetries, maxRetries = 3, delayBetweenRetries = 1e3) {
  let app;
  let url;
  let requestOptions;
  let rateLimiter;
  if (typeof appOrUrl === "string") {
    url = appOrUrl;
    requestOptions = urlOrOptions;
    rateLimiter = optionsOrRateLimiter;
    if (typeof rateLimiterOrMaxRetries === "number") {
      maxRetries = rateLimiterOrMaxRetries;
    }
  } else {
    app = appOrUrl;
    url = urlOrOptions;
    requestOptions = optionsOrRateLimiter;
    rateLimiter = rateLimiterOrMaxRetries;
  }
  for (let attemptNumber = 0; attemptNumber < maxRetries; attemptNumber++) {
    const isLastAttempt = attemptNumber === maxRetries - 1;
    try {
      await rateLimiter.checkLimit();
      const response = await (0, import_obsidian.request)({
        url,
        method: requestOptions.method || "GET",
        headers: requestOptions.headers,
        body: requestOptions.body
      });
      return parseApiResponse(response);
    } catch (error) {
      if (!await handleRequestError(error, rateLimiter, attemptNumber, maxRetries, delayBetweenRetries) && isLastAttempt) {
        throw error;
      }
    }
  }
  throw new Error("Request failed after maximum retry attempts");
}

// src/utils/yamlUtils.ts
var import_obsidian2 = require("obsidian");

// src/main.ts
var RaindropTypes = {
  LINK: "link",
  ARTICLE: "article",
  IMAGE: "image",
  VIDEO: "video",
  DOCUMENT: "document",
  AUDIO: "audio"
};
var TagMatchTypes = {
  ALL: "all",
  ANY: "any"
};
var SystemCollections = {
  UNSORTED: -1,
  TRASH: -99
};
var FilterTypes = {
  ...RaindropTypes,
  ALL: "all"
};
var DEFAULT_SETTINGS = {
  apiToken: "",
  defaultFolder: "",
  fileNameTemplate: "{{title}}",
  showRibbonIcon: true,
  bannerFieldName: "banner",
  isTemplateSystemEnabled: true,
  defaultTemplate: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

{{#if cover}}
![{{title}}]({{cover}})
{{/if}}

# {{title}}

{{#if excerpt}}
## Description
{{excerpt}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

{{#if highlights}}
## Highlights
{{#each highlights}}
- {{text}}
{{#if note}}  *Note:* {{note}}{{/if}}
{{/each}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}
`,
  contentTypeTemplates: {
    link: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

{{#if cover}}
![{{title}}]({{cover}})
{{/if}}

# {{title}}

{{#if excerpt}}
## Description
{{excerpt}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

{{#if highlights}}
## Highlights
{{#each highlights}}
- {{text}}
{{#if note}}  *Note:* {{note}}{{/if}}
{{/each}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[Source]({{link}})`,
    article: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

{{#if cover}}
![{{title}}]({{cover}})
{{/if}}

# {{title}}

{{#if excerpt}}
## Summary
{{excerpt}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

{{#if highlights}}
## Key Points
{{#each highlights}}
> {{text}}
{{#if note}}  *Note:* {{note}}{{/if}}
{{/each}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[Read Article]({{link}})`,
    image: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{bannerFieldName}}: {{cover}}
---

![{{title}}]({{cover}})

{{#if excerpt}}
*{{excerpt}}*
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[View Original]({{link}})`,
    video: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

{{#if cover}}
![{{title}}]({{cover}})
{{/if}}

# {{title}}

{{#if excerpt}}
## Description
{{excerpt}}
{{/if}}

{{#if highlights}}
## Timestamps
{{#each highlights}}
- {{text}}
{{#if note}}  *Comment:* {{note}}{{/if}}
{{/each}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[Watch Video]({{link}})`,
    document: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

# {{title}}

{{#if excerpt}}
## Summary
{{excerpt}}
{{/if}}

{{#if highlights}}
## Key Points
{{#each highlights}}
- {{text}}
{{#if note}}  *Note:* {{note}}{{/if}}
{{/each}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[Open Document]({{link}})`,
    audio: `---
title: "{{title}}"
source: {{link}}
type: {{type}}
created: {{created}}
lastupdate: {{lastupdate}}
id: {{id}}
collectionId: {{collectionId}}
collectionTitle: "{{collectionTitle}}"
collectionPath: "{{collectionPath}}"
{{#if collectionParentId}}collectionParentId: {{collectionParentId}}{{/if}}
tags:
{{#each tags}}
  - {{this}}
{{/each}}
{{#if cover}}
{{bannerFieldName}}: {{cover}}
{{/if}}
---

{{#if cover}}
![{{title}}]({{cover}})
{{/if}}

# {{title}}

{{#if excerpt}}
## Description
{{excerpt}}
{{/if}}

{{#if highlights}}
## Timestamps
{{#each highlights}}
- {{text}}
{{#if note}}  *Comment:* {{note}}{{/if}}
{{/each}}
{{/if}}

{{#if note}}
## Notes
{{note}}
{{/if}}

---
## Details
- **Type**: {{renderedType}}
- **Domain**: {{domain}}
- **Created**: {{formattedCreatedDate}}
- **Updated**: {{formattedUpdatedDate}}
- **Tags**: {{formattedTags}}

[Listen to Audio]({{link}})`
  },
  contentTypeTemplateToggles: {
    link: true,
    article: true,
    image: true,
    video: true,
    document: true,
    audio: true
  }
};
var RaindropFetchModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.collections = "";
    this.apiFilterTags = "";
    this.includeSubcollections = false;
    this.appendTagsToNotes = "";
    this.useRaindropTitleForFileName = true;
    this.tagMatchType = "all";
    this.filterType = "all";
    this.fetchOnlyNew = false;
    this.updateExisting = false;
    this.useDefaultTemplate = false;
    this.overrideTemplates = false;
    this.plugin = plugin;
    this.vaultPath = this.plugin.settings.defaultFolder;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("make-it-rain-modal");
    contentEl.createEl("h2", { text: "Make It Rain: Fetch Options" });
    contentEl.createEl("h3", { text: "\u{1F3AF} Fetch Criteria" });
    new import_obsidian3.Setting(contentEl).setName("Vault Save Location").setDesc("Override default save folder for this fetch. Leave blank for default.").setClass("setting-item-stacked").addText((text) => {
      text.setPlaceholder(this.plugin.settings.defaultFolder || "Vault Root").setValue(this.vaultPath).onChange((value) => {
        this.vaultPath = value;
      });
      text.inputEl.style.width = "100%";
    });
    let collectionsTextComponent;
    new import_obsidian3.Setting(contentEl).setName("Filter by Collections").setDesc("Comma-separated Raindrop Collection IDs or Names. Click a collection below to add its name. If typing names manually, use IDs for duplicate collection names to ensure accuracy.").setClass("setting-item-stacked").addText((text) => {
      collectionsTextComponent = text;
      text.setPlaceholder("e.g., 12345, My Work, Work > Articles").setValue(this.collections).onChange((value) => {
        this.collections = value;
      });
      text.inputEl.style.width = "100%";
    });
    const collectionsContainer = contentEl.createDiv({ cls: "make-it-rain-collections-container" });
    collectionsContainer.style.maxHeight = "150px";
    collectionsContainer.style.overflowY = "auto";
    collectionsContainer.style.border = "1px solid var(--background-modifier-border)";
    collectionsContainer.style.borderRadius = "var(--radius-m)";
    collectionsContainer.style.padding = "10px";
    collectionsContainer.style.marginTop = "5px";
    collectionsContainer.style.marginBottom = "10px";
    const loadingCollectionsEl = collectionsContainer.createEl("p", { text: "Loading your collections...", cls: "make-it-rain-loading-collections" });
    this.plugin.fetchAllUserCollections().then((fetchedCollections) => {
      loadingCollectionsEl.remove();
      if (fetchedCollections && fetchedCollections.length > 0) {
        const listEl = collectionsContainer.createEl("ul", { cls: "make-it-rain-collection-list" });
        listEl.style.listStyleType = "none";
        listEl.style.paddingLeft = "0";
        listEl.style.margin = "0";
        const collectionMap = /* @__PURE__ */ new Map();
        fetchedCollections.forEach((col) => collectionMap.set(col._id, col));
        const getDisplayPath = (collection) => {
          var _a;
          const pathSegments = [];
          let current = collection;
          while (current) {
            pathSegments.unshift(current.title);
            const parentId = (_a = current.parent) == null ? void 0 : _a.$id;
            current = parentId ? collectionMap.get(parentId) : void 0;
          }
          return pathSegments.join(" > ");
        };
        const collectionsWithDisplayPaths = fetchedCollections.map((collection) => ({
          ...collection,
          displayPath: getDisplayPath(collection)
        }));
        collectionsWithDisplayPaths.sort((a, b) => a.displayPath.localeCompare(b.displayPath));
        collectionsWithDisplayPaths.forEach((collection) => {
          const listItemEl = listEl.createEl("li", {
            text: `${collection.displayPath} (ID: ${collection._id})`,
            cls: "make-it-rain-collection-item"
          });
          listItemEl.style.padding = "5px";
          listItemEl.style.cursor = "pointer";
          listItemEl.style.borderBottom = "1px solid var(--background-modifier-border-hover)";
          listItemEl.onmouseover = () => listItemEl.style.backgroundColor = "var(--background-modifier-hover)";
          listItemEl.onmouseout = () => listItemEl.style.backgroundColor = "transparent";
          listItemEl.addEventListener("click", () => {
            const currentInputValue = collectionsTextComponent.getValue().trim();
            const collectionNameToAdd = collection.title;
            if (currentInputValue === "") {
              collectionsTextComponent.setValue(collectionNameToAdd);
            } else {
              const existingInputs = currentInputValue.split(",").map((s) => s.trim());
              if (!existingInputs.includes(collectionNameToAdd)) {
                collectionsTextComponent.setValue(currentInputValue + ", " + collectionNameToAdd);
              }
            }
            this.collections = collectionsTextComponent.getValue();
          });
        });
      } else {
        collectionsContainer.createEl("p", { text: "No collections found, or failed to load them. Please check API token or try again.", cls: "make-it-rain-collections-error" });
      }
    }).catch((error) => {
      loadingCollectionsEl.remove();
      collectionsContainer.createEl("p", { text: "Error loading collections. See console for details.", cls: "make-it-rain-collections-error" });
      console.error("Failed to load collections into modal:", error);
    });
    new import_obsidian3.Setting(contentEl).setName("Include Subcollections").setDesc("If filtering by Collections, also fetch from their subcollections.").addToggle((toggle) => {
      toggle.setValue(this.includeSubcollections).onChange((value) => {
        this.includeSubcollections = value;
      });
    });
    new import_obsidian3.Setting(contentEl).setName("Filter by Tags").setDesc("Comma-separated Raindrop tag names.").setClass("setting-item-stacked").addText((text) => {
      text.setPlaceholder("e.g., obsidian, productivity, to-read").setValue(this.apiFilterTags).onChange((value) => {
        this.apiFilterTags = value;
      });
      text.inputEl.style.width = "100%";
    });
    const tagMatchSetting = new import_obsidian3.Setting(contentEl).setName("Tag Match Type").setDesc("Choose 'ALL' for items with all specified tags, 'ANY' for items with any.").addDropdown((dropdown) => {
      dropdown.addOption(TagMatchTypes.ALL, "Match ALL Tags (AND)").addOption(TagMatchTypes.ANY, "Match ANY Tag (OR)").setValue(this.tagMatchType).onChange((value) => {
        this.tagMatchType = value;
      });
    });
    const tagMatchHelpLink = tagMatchSetting.nameEl.createEl("a", {
      href: "https://frostmute.github.io/make-it-rain/usage#tag-match-type",
      // Placeholder URL
      text: " (?)",
      cls: "make-it-rain-help-link",
      title: "Documentation for Tag Match Type"
    });
    tagMatchHelpLink.setAttr("target", "_blank");
    new import_obsidian3.Setting(contentEl).setName("Filter by Content Type").setDesc("Select the type of Raindrops to fetch.").addDropdown((dropdown) => {
      dropdown.addOption(FilterTypes.ALL, "All Types");
      Object.values(RaindropTypes).forEach((type) => {
        dropdown.addOption(type, type.charAt(0).toUpperCase() + type.slice(1));
      });
      dropdown.setValue(this.filterType).onChange((value) => {
        this.filterType = value;
      });
    });
    contentEl.createEl("h3", { text: "\u{1F4DD} Note Options" });
    const appendTagsSetting = new import_obsidian3.Setting(contentEl).setName("Append Tags to Notes").setDesc("Comma-separated tags to add to the frontmatter of each created note.").setClass("setting-item-stacked");
    const appendTagsDescEl = appendTagsSetting.descEl.createEl("p", {
      cls: "make-it-rain-input-hint",
      text: "Tip: Start tags with #. Spaces will be converted to underscores during processing."
    });
    appendTagsDescEl.style.fontSize = "var(--font-ui-smaller)";
    appendTagsDescEl.style.color = "var(--text-muted)";
    appendTagsDescEl.style.marginTop = "4px";
    appendTagsSetting.addText((text) => {
      text.setPlaceholder("e.g., #imported, #raindrop, my tag").setValue(this.appendTagsToNotes).onChange((value) => {
        this.appendTagsToNotes = value;
        const tags = value.split(",").map((t) => t.trim()).filter((t) => t !== "");
        let hintText = "Tip: Start tags with #. Spaces will be converted to underscores.";
        let hasIssues = false;
        if (tags.length > 0) {
          const issues = [];
          if (tags.some((t) => !t.startsWith("#"))) {
            issues.push("some tags don't start with #");
            hasIssues = true;
          }
          if (tags.some((t) => t.includes(" ") && t.includes("#"))) {
            issues.push("tags with # shouldn't contain spaces (use hyphens or underscores)");
            hasIssues = true;
          }
          if (hasIssues) {
            hintText = `Heads up: ${issues.join("; ")}.`;
          }
        }
        appendTagsDescEl.textContent = hintText;
        appendTagsDescEl.style.color = hasIssues ? "var(--text-warning)" : "var(--text-muted)";
      });
      text.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).setName("Use Raindrop Title for Filename").setDesc("If off, Raindrop ID will be used. Uses filename template from settings.").addToggle((toggle) => {
      toggle.setValue(this.useRaindropTitleForFileName).onChange((value) => {
        this.useRaindropTitleForFileName = value;
      });
    });
    const fetchOnlyNewToggle = new import_obsidian3.Setting(contentEl).setName("Fetch Only New Items").setDesc("Skip Raindrops if a note with the same filename already exists.").addToggle((toggle) => {
      toggle.setValue(this.fetchOnlyNew).onChange((value) => {
        this.fetchOnlyNew = value;
        if (value && this.updateExisting) {
          this.updateExisting = false;
          const updateExistingInput = contentEl.querySelector('.update-existing-toggle input[type="checkbox"]');
          if (updateExistingInput) updateExistingInput.checked = false;
        }
      });
    });
    new import_obsidian3.Setting(contentEl).setName("Update Existing Notes").setDesc('Update notes if Raindrop item changed (based on ID & last_update). Overrides "Fetch only new".').setClass("update-existing-toggle").addToggle((toggle) => {
      toggle.setValue(this.updateExisting).onChange((value) => {
        this.updateExisting = value;
        if (value && this.fetchOnlyNew) {
          this.fetchOnlyNew = false;
          const fetchNewInput = fetchOnlyNewToggle.controlEl.querySelector('input[type="checkbox"]');
          if (fetchNewInput) fetchNewInput.checked = false;
        }
      });
    });
    if (this.plugin.settings.isTemplateSystemEnabled) {
      contentEl.createEl("h3", { text: "\u{1F4C4} Template Overrides (Optional)" });
      const defaultTemplateToggle = new import_obsidian3.Setting(contentEl).setName("Use Default Template Only").setDesc("Ignore content type specific templates and use the default template for all items this fetch.").addToggle((toggle) => {
        toggle.setValue(this.useDefaultTemplate).onChange((value) => {
          this.useDefaultTemplate = value;
          const overrideTemplatesInput = contentEl.querySelector('.override-templates-toggle input[type="checkbox"]');
          if (value && overrideTemplatesInput) {
            this.overrideTemplates = false;
            overrideTemplatesInput.checked = false;
            overrideTemplatesInput.disabled = true;
          } else if (overrideTemplatesInput) {
            overrideTemplatesInput.disabled = false;
          }
        });
      });
      new import_obsidian3.Setting(contentEl).setClass("override-templates-toggle").setName("Force Use of Content-Type Templates").setDesc("Use specific content-type templates even if they are disabled in global settings (for this fetch only).").addToggle((toggle) => {
        toggle.setValue(this.overrideTemplates).setDisabled(this.useDefaultTemplate).onChange((value) => {
          this.overrideTemplates = value;
        });
      });
    } else {
      contentEl.createEl("p", {
        text: "Template system is disabled. Enable it in plugin settings to customize note output and see template override options here.",
        cls: "setting-item-description"
      });
    }
    contentEl.createEl("hr");
    const buttonsEl = contentEl.createDiv({ cls: "modal-button-container" });
    new import_obsidian3.ButtonComponent(buttonsEl).setButtonText("Fetch Raindrops").setCta().onClick(async () => {
      const options = {
        vaultPath: this.vaultPath || void 0,
        // Use undefined if empty to signify default
        collections: this.collections,
        apiFilterTags: this.apiFilterTags,
        includeSubcollections: this.includeSubcollections,
        appendTagsToNotes: this.appendTagsToNotes,
        useRaindropTitleForFileName: this.useRaindropTitleForFileName,
        tagMatchType: this.tagMatchType,
        filterType: this.filterType,
        fetchOnlyNew: this.fetchOnlyNew,
        updateExisting: this.updateExisting,
        useDefaultTemplate: this.useDefaultTemplate,
        overrideTemplates: this.overrideTemplates
      };
      this.close();
      await this.plugin.fetchRaindrops(options);
    });
    new import_obsidian3.ButtonComponent(buttonsEl).setButtonText("Cancel").onClick(() => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var QuickImportModal = class extends import_obsidian3.Modal {
  // Added appendTagsToNotes
  constructor(app, plugin) {
    super(app);
    this.itemUrlOrId = "";
    this.appendTagsToNotes = "";
    this.plugin = plugin;
    this.vaultPath = this.plugin.settings.defaultFolder;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("make-it-rain-modal");
    contentEl.createEl("h2", { text: "Quick Import Raindrop" });
    new import_obsidian3.Setting(contentEl).setName("Raindrop URL or ID").setDesc(
      `How to find: In the Raindrop.io app, click "Edit" on the specific item (or look for a similar action that opens the item in a detailed/edit view). The URL in your browser's address bar should look like ".../item/[ID]/edit" or similar. You can paste this full URL here, or just the numeric ID (e.g., 12345678).`
    ).setClass("setting-item-stacked").addText((text) => {
      text.setPlaceholder("e.g., https://.../item/12345678/edit or 12345678").setValue(this.itemUrlOrId).onChange((value) => {
        this.itemUrlOrId = value.trim();
      });
      text.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).setName("Vault Save Location (Optional)").setDesc("Override default save folder. Leave blank for plugin default.").addText((text) => {
      text.setPlaceholder(this.plugin.settings.defaultFolder || "Vault Root").setValue(this.vaultPath).onChange((value) => {
        this.vaultPath = value.trim();
      });
      text.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).setName("Append Tags to Notes (Optional)").setDesc("Comma-separated tags to add to the frontmatter of the created note.").addText((text) => {
      text.setPlaceholder("e.g., #quickimport, #todo").setValue(this.appendTagsToNotes).onChange((value) => {
        this.appendTagsToNotes = value.trim();
      });
      text.inputEl.style.width = "100%";
    });
    const buttonsEl = contentEl.createDiv({ cls: "modal-button-container" });
    new import_obsidian3.ButtonComponent(buttonsEl).setButtonText("Fetch & Create Note").setCta().onClick(async () => {
      if (!this.itemUrlOrId) {
        new import_obsidian3.Notice("Please enter a Raindrop URL or ID.", 5e3);
        return;
      }
      let itemId = null;
      if (/^\d{8,}$/.test(this.itemUrlOrId)) {
        itemId = parseInt(this.itemUrlOrId, 10);
      } else {
        const urlPatternMatch = this.itemUrlOrId.match(/(\d{8,})/);
        if (urlPatternMatch && urlPatternMatch[1]) {
          itemId = parseInt(urlPatternMatch[1], 10);
        }
      }
      if (!itemId) {
        new import_obsidian3.Notice("Could not parse a valid Raindrop ID (at least 8 digits) from the input.", 7e3);
        return;
      }
      this.close();
      await this.plugin.fetchSingleRaindrop(itemId, this.vaultPath || void 0, this.appendTagsToNotes || void 0);
    });
    new import_obsidian3.ButtonComponent(buttonsEl).setButtonText("Cancel").onClick(() => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var RaindropToObsidian = class extends import_obsidian3.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.isRibbonShown = false;
    this.settings = { ...DEFAULT_SETTINGS };
    this.rateLimiter = createRateLimiter();
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "fetch-raindrops",
      name: "Fetch Raindrops (Filtered)",
      callback: async () => {
        new RaindropFetchModal(this.app, this).open();
      }
    });
    this.addCommand({
      // New command for Quick Import
      id: "quick-import-raindrop",
      name: "Quick Import Raindrop by URL/ID",
      callback: async () => {
        new QuickImportModal(this.app, this).open();
      }
    });
    this.updateRibbonIcon();
    this.addSettingTab(new RaindropToObsidianSettingTab(this.app, this));
    console.log("Make It Rain plugin loaded!");
  }
  onunload() {
    var _a;
    (_a = this.ribbonIconEl) == null ? void 0 : _a.remove();
    console.log("Make It Rain plugin unloaded.");
  }
  async loadSettings() {
    const savedData = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS };
    if (savedData) {
      const mergedSettings = {
        ...this.settings,
        ...savedData,
        contentTypeTemplates: {
          ...this.settings.contentTypeTemplates,
          ...Object.fromEntries(
            Object.entries(savedData.contentTypeTemplates || {}).map(([key, value]) => [
              key,
              value.trim() === "" ? this.settings.contentTypeTemplates[key] : value
            ])
          )
        },
        contentTypeTemplateToggles: {
          ...this.settings.contentTypeTemplateToggles,
          ...savedData.contentTypeTemplateToggles || {}
        }
      };
      this.settings = mergedSettings;
    }
    await this.saveSettings();
  }
  getTemplateForType(type, options) {
    var _a;
    if (options.useDefaultTemplate) {
      return this.settings.defaultTemplate;
    }
    const shouldUseTypeTemplate = options.overrideTemplates || this.settings.contentTypeTemplateToggles[type] && ((_a = this.settings.contentTypeTemplates[type]) == null ? void 0 : _a.trim()) !== "";
    return shouldUseTypeTemplate ? this.settings.contentTypeTemplates[type] : this.settings.defaultTemplate;
  }
  /**
   * Generates a file name based on the provided raindrop data and settings
   * @param raindrop - The raindrop data to use for file name generation
   * @param useRaindropTitleForFileName - Whether to use the raindrop title for the file name
   * @returns The generated file name
   */
  generateFileName(raindrop, useRaindropTitleForFileName) {
    var _a;
    const fileNameTemplate = useRaindropTitleForFileName ? this.settings.fileNameTemplate : "{{id}}";
    let fileName = fileNameTemplate;
    const replacePlaceholder = (placeholder, value) => {
      const safeValue = sanitizeFileName(value);
      const regex = new RegExp(`{{${placeholder}}}`, "gi");
      fileName = fileName.replace(regex, safeValue);
    };
    try {
      replacePlaceholder("title", raindrop.title || "Untitled");
      replacePlaceholder("id", (raindrop._id || "unknown_id").toString());
      replacePlaceholder("collectionTitle", ((_a = raindrop.collection) == null ? void 0 : _a.title) || "No Collection");
      const createdDate = raindrop.created ? new Date(raindrop.created) : null;
      let formattedDate = "no_date";
      if (createdDate && !isNaN(createdDate.getTime())) {
        formattedDate = createdDate.toISOString().split("T")[0];
      }
      replacePlaceholder("date", formattedDate);
    } catch (error) {
      let errorMsg = "template processing error";
      if (error instanceof Error) errorMsg = error.message;
      console.error("Error processing file name template:", errorMsg, error);
      new import_obsidian3.Notice("Error generating file name. Check console or template.");
      return "Error_Filename_" + Date.now();
    }
    let finalFileName = sanitizeFileName(fileName);
    if (!finalFileName.trim()) {
      return "Unnamed_Raindrop_" + (raindrop._id || Date.now());
    }
    return finalFileName;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  sanitizeFileName(name) {
    return sanitizeFileName(name);
  }
  /**
   * Update the ribbon icon based on settings
   */
  updateRibbonIcon() {
    var _a;
    (_a = this.ribbonIconEl) == null ? void 0 : _a.remove();
    this.ribbonIconEl = void 0;
    if (this.settings.showRibbonIcon) {
      this.ribbonIconEl = this.addRibbonIcon(
        "cloud-download",
        // Obsidian icon ID for cloud download
        "Fetch Raindrops",
        // Tooltip text
        () => {
          new RaindropFetchModal(this.app, this).open();
        }
      );
    }
  }
  async fetchRaindrops(options) {
    var _a;
    const baseApiUrl = "https://api.raindrop.io/rest/v1";
    const fetchOptions = {
      method: "GET",
      headers: {
        "Authorization": `Bearer ${this.settings.apiToken}`
      }
    };
    const loadingNotice = new import_obsidian3.Notice("Starting Raindrop fetch...", 0);
    try {
      let allData = [];
      const perPage = 50;
      if (!this.settings.apiToken) {
        loadingNotice.hide();
        new import_obsidian3.Notice("Please configure your Raindrop.io API token in the plugin settings.", 1e4);
        return;
      }
      let resolvedCollectionIds = [];
      const collectionNameToIdMap = /* @__PURE__ */ new Map();
      const collectionIdToNameMap = /* @__PURE__ */ new Map();
      const collectionHierarchy = /* @__PURE__ */ new Map();
      let collectionsData = void 0;
      if (options.collections) {
        const collectionInputs = options.collections.split(",").map((input) => input.trim()).filter((input) => input !== "");
        loadingNotice.setMessage("Fetching user collections...");
        const rootCollectionsResponse = await fetchWithRetry(
          `${baseApiUrl}/collections`,
          fetchOptions,
          this.rateLimiter
        );
        const rootCollectionsData = rootCollectionsResponse;
        const nestedCollectionsResponse = await fetchWithRetry(
          `${baseApiUrl}/collections/childrens`,
          fetchOptions,
          this.rateLimiter
        );
        const nestedCollectionsData = nestedCollectionsResponse;
        let allCollections = [];
        if ((rootCollectionsData == null ? void 0 : rootCollectionsData.result) && (rootCollectionsData == null ? void 0 : rootCollectionsData.items)) {
          allCollections = allCollections.concat(rootCollectionsData.items);
        }
        if ((nestedCollectionsData == null ? void 0 : nestedCollectionsData.result) && (nestedCollectionsData == null ? void 0 : nestedCollectionsData.items)) {
          allCollections = allCollections.concat(nestedCollectionsData.items);
        }
        if (allCollections.length === 0) {
          console.error("API Error fetching collections: No collections returned from both endpoints.");
          loadingNotice.hide();
          new import_obsidian3.Notice("Error fetching user collections. Please check your API token and connection.", 1e4);
          return;
        }
        allCollections.forEach((col) => {
          var _a2;
          collectionNameToIdMap.set(col.title.toLowerCase(), col._id);
          collectionIdToNameMap.set(col._id, col.title);
          collectionHierarchy.set(col._id, { title: col.title, parentId: (_a2 = col.parent) == null ? void 0 : _a2.$id });
        });
        collectionsData = { result: true, items: allCollections };
        const unresolvedInputs = [];
        for (const input of collectionInputs) {
          const inputAsNumber = parseInt(input, 10);
          if (!isNaN(inputAsNumber)) {
            if (collectionIdToNameMap.has(inputAsNumber)) {
              resolvedCollectionIds.push(inputAsNumber);
            } else {
              unresolvedInputs.push(input);
              console.warn(`Could not find collection with ID: ${input}`);
            }
          } else {
            const resolvedId = collectionNameToIdMap.get(input.toLowerCase());
            if (resolvedId !== void 0) {
              resolvedCollectionIds.push(resolvedId);
            } else {
              unresolvedInputs.push(input);
              console.warn(`Could not resolve collection name: ${input}`);
            }
          }
        }
        if (unresolvedInputs.length > 0) {
          new import_obsidian3.Notice(`Could not find collections: ${unresolvedInputs.join(", ")}. Please check names or use IDs.`, 15e3);
        }
        if (resolvedCollectionIds.length === 0 && collectionInputs.length > 0) {
          loadingNotice.hide();
          new import_obsidian3.Notice("No valid collection IDs or names provided.", 5e3);
          return;
        }
        resolvedCollectionIds = Array.from(new Set(resolvedCollectionIds));
      } else {
        loadingNotice.setMessage("Fetching all collections...");
        const rootCollectionsResponse = await fetchWithRetry(
          `${baseApiUrl}/collections`,
          fetchOptions,
          this.rateLimiter
        );
        const rootCollectionsData = rootCollectionsResponse;
        const nestedCollectionsResponse = await fetchWithRetry(
          `${baseApiUrl}/collections/childrens`,
          fetchOptions,
          this.rateLimiter
        );
        const nestedCollectionsData = nestedCollectionsResponse;
        let allCollections = [];
        if ((rootCollectionsData == null ? void 0 : rootCollectionsData.result) && (rootCollectionsData == null ? void 0 : rootCollectionsData.items)) {
          allCollections = allCollections.concat(rootCollectionsData.items);
        }
        if ((nestedCollectionsData == null ? void 0 : nestedCollectionsData.result) && (nestedCollectionsData == null ? void 0 : nestedCollectionsData.items)) {
          allCollections = allCollections.concat(nestedCollectionsData.items);
        }
        if (allCollections.length === 0) {
          console.error("API Error fetching collections: No collections returned from both endpoints.");
          loadingNotice.hide();
          new import_obsidian3.Notice("Error fetching user collections. Please check your API token and connection.", 1e4);
          return;
        }
        allCollections.forEach((col) => {
          var _a2;
          collectionNameToIdMap.set(col.title.toLowerCase(), col._id);
          collectionIdToNameMap.set(col._id, col.title);
          collectionHierarchy.set(col._id, { title: col.title, parentId: (_a2 = col.parent) == null ? void 0 : _a2.$id });
        });
        collectionsData = { result: true, items: allCollections };
      }
      const searchParameterString = options.apiFilterTags.split(",").map((tag) => tag.trim()).filter((tag) => tag !== "").join(" ");
      let fetchMode = "all";
      if (resolvedCollectionIds.length > 0) {
        fetchMode = "collections";
      } else if (searchParameterString || options.tagMatchType === TagMatchTypes.ANY && options.apiFilterTags.length > 0) {
        fetchMode = "tags";
      }
      if (fetchMode === "collections") {
        for (const collectionId of resolvedCollectionIds) {
          let hasMore = true;
          let page = 0;
          const collectionApiBaseUrl = `${baseApiUrl}/raindrops/${collectionId}`;
          while (hasMore) {
            const params = new URLSearchParams({
              perpage: perPage.toString(),
              page: page.toString()
            });
            if (options.filterType && options.filterType !== "all") {
              params.append("type", options.filterType);
            }
            if (searchParameterString) {
              params.append("search", searchParameterString);
            }
            if (options.includeSubcollections) {
              params.append("nested", "true");
            }
            const currentApiUrl = `${collectionApiBaseUrl}?${params.toString()}`;
            console.log(`Requesting items from collection ID: ${collectionId}`, currentApiUrl);
            const collectionNameForNotice = collectionIdToNameMap.get(collectionId) || collectionId.toString();
            loadingNotice.setMessage(`Fetching from collection: ${collectionNameForNotice}, page ${page + 1}...`);
            const response = await fetchWithRetry(
              currentApiUrl,
              fetchOptions,
              this.rateLimiter
            );
            const data = response;
            if (!data.result) {
              console.error(`API Error for collection ${collectionId}:`, data);
              new import_obsidian3.Notice(`Error fetching collection: ${collectionNameForNotice}. Skipping.`, 7e3);
              hasMore = false;
              continue;
            }
            if (data == null ? void 0 : data.items) {
              allData = allData.concat(data.items);
              page++;
              hasMore = data.items.length === perPage;
              console.log(`Fetched ${data.items.length} items from collection ${collectionId}, page ${page}`);
              if (hasMore) {
                loadingNotice.setMessage(`Fetching from collection: ${collectionNameForNotice}, page ${page + 1}...`);
              }
            } else {
              console.warn(`Unexpected response for collection ${collectionId}. Stopping.`);
              hasMore = false;
            }
          }
        }
      } else if (fetchMode === "tags") {
        if (options.tagMatchType === TagMatchTypes.ANY && options.apiFilterTags.length > 0) {
          const uniqueItems = /* @__PURE__ */ new Map();
          const tagsArray = options.apiFilterTags.split(",").map((tag) => tag.trim()).filter((tag) => tag !== "");
          for (const tag of tagsArray) {
            let hasMore = true;
            let page = 0;
            while (hasMore) {
              const params = new URLSearchParams({
                perpage: perPage.toString(),
                page: page.toString(),
                search: `#${tag}`
                // Simple, reliable single-tag search
              });
              if (options.filterType && options.filterType !== "all") {
                params.append("type", options.filterType);
              }
              const currentApiUrl = `${baseApiUrl}/raindrops/0?${params.toString()}`;
              console.log(`Requesting items with tag: ${tag}`, currentApiUrl);
              loadingNotice.setMessage(`Fetching items with tag: ${tag}, page ${page + 1}...`);
              const response = await fetchWithRetry(
                currentApiUrl,
                fetchOptions,
                this.rateLimiter
              );
              const data = response;
              if (!data.result) {
                console.error(`API Error for tag ${tag}:`, data);
                continue;
              }
              console.log(`API Response for tag ${tag}:`, {
                result: data.result,
                itemCount: ((_a = data == null ? void 0 : data.items) == null ? void 0 : _a.length) || 0,
                totalCount: (data == null ? void 0 : data.count) || 0
              });
              if (data == null ? void 0 : data.items) {
                data.items.forEach((item) => {
                  if (!uniqueItems.has(item._id)) {
                    uniqueItems.set(item._id, item);
                  }
                });
                page++;
                hasMore = data.items.length === perPage;
                console.log(`Fetched ${data.items.length} items for tag ${tag}, page ${page}`);
                if (hasMore) {
                  loadingNotice.setMessage(`Fetching items with tag: ${tag}, page ${page + 1}...`);
                }
              } else {
                hasMore = false;
              }
            }
          }
          allData = Array.from(uniqueItems.values());
          console.log(`Total unique items found across all tags: ${allData.length}`);
        } else if (searchParameterString) {
          let hasMore = true;
          let page = 0;
          while (hasMore) {
            const params = new URLSearchParams({
              perpage: perPage.toString(),
              page: page.toString(),
              search: searchParameterString
              // This handles space-separated tags for AND logic
            });
            if (options.filterType && options.filterType !== "all") {
              params.append("type", options.filterType);
            }
            const currentApiUrl = `${baseApiUrl}/raindrops/0?${params.toString()}`;
            console.log(`Requesting items with tags: ${searchParameterString}`, currentApiUrl);
            loadingNotice.setMessage(`Fetching items with tags: ${searchParameterString}, page ${page + 1}...`);
            const response = await fetchWithRetry(
              currentApiUrl,
              fetchOptions,
              this.rateLimiter
            );
            const data = response;
            if (!data.result) {
              console.error("API Error for tag search:", data);
              throw new Error(`API Error: ${JSON.stringify(data)}`);
            }
            if (data == null ? void 0 : data.items) {
              allData = allData.concat(data.items);
              page++;
              hasMore = data.items.length === perPage;
              console.log(`Fetched ${data.items.length} items with tags, page ${page}`);
              if (hasMore) {
                loadingNotice.setMessage(`Fetching items with tags: ${searchParameterString}, page ${page + 1}...`);
              }
            } else {
              hasMore = false;
            }
          }
        }
      } else {
        let hasMore = true;
        let page = 0;
        while (hasMore) {
          const params = new URLSearchParams({ perpage: perPage.toString(), page: page.toString() });
          if (options.filterType && options.filterType !== "all") {
            params.append("type", options.filterType);
          }
          const currentApiUrl = `${baseApiUrl}/raindrops/0?${params.toString()}`;
          console.log("Requesting all items:", currentApiUrl);
          loadingNotice.setMessage(`Fetching all items, page ${page + 1}...`);
          const response = await fetchWithRetry(
            currentApiUrl,
            fetchOptions,
            this.rateLimiter
          );
          const data = response;
          if (!data.result) {
            console.error("API Error for all items fetch:", data);
            throw new Error(`API Error: ${JSON.stringify(data)}`);
          }
          if (data == null ? void 0 : data.items) {
            allData = allData.concat(data.items);
            page++;
            hasMore = data.items.length === perPage;
            console.log(`Fetched ${data.items.length} items, page ${page}`);
            if (hasMore) {
              loadingNotice.setMessage(`Fetching all items, page ${page + 1}...`);
            }
          } else {
            console.warn("Unexpected response for all items fetch. Stopping.");
            hasMore = false;
          }
        }
      }
      if (allData.length === 0) {
        if (resolvedCollectionIds.length > 0 || searchParameterString || options.tagMatchType === TagMatchTypes.ANY && options.apiFilterTags.length > 0) {
          loadingNotice.hide();
          new import_obsidian3.Notice("No raindrops found matching your criteria.", 5e3);
        } else {
          loadingNotice.hide();
          new import_obsidian3.Notice("No raindrops found in your account.", 5e3);
        }
      } else {
        loadingNotice.setMessage(`Found ${allData.length} raindrops. Applying type filter...`);
        let filteredData = allData;
        if (options.filterType && options.filterType !== "all") {
          filteredData = allData.filter((item) => item.type === options.filterType);
          loadingNotice.setMessage(`Found ${filteredData.length} raindrops of type '${options.filterType}'. Processing...`);
          if (filteredData.length === 0) {
            new import_obsidian3.Notice(`No raindrops found matching type '${options.filterType}'.`, 5e3);
            loadingNotice.hide();
            return;
          }
        } else {
          loadingNotice.setMessage(`Found ${allData.length} raindrops. Processing...`);
        }
        await this.processRaindrops(filteredData, options.vaultPath, options.appendTagsToNotes, options.useRaindropTitleForFileName, loadingNotice, options, collectionsData, resolvedCollectionIds, collectionIdToNameMap);
      }
    } catch (error) {
      loadingNotice.hide();
      let errorMessage = "An unknown error occurred during fetch";
      if (error instanceof Error) errorMessage = error.message;
      else if (typeof error === "string") errorMessage = error;
      new import_obsidian3.Notice(`Error fetching raindrops: ${errorMessage}`, 1e4);
      console.error("Error fetching Raindrop API:", error);
    }
  }
  async processRaindrops(raindrops, vaultPath, appendTagsToNotes, useRaindropTitleForFileName, loadingNotice, options, collectionsData, resolvedCollectionIds = [], collectionIdToNameMap = /* @__PURE__ */ new Map()) {
    var _a, _b;
    const { app } = this;
    const settingsFMTags = appendTagsToNotes.split(",").map((tag) => tag.trim()).filter((tag) => tag !== "");
    if (vaultPath === void 0) vaultPath = this.settings.defaultFolder;
    const baseTargetFolderPath = (vaultPath == null ? void 0 : vaultPath.trim()) ? (0, import_obsidian3.normalizePath)(vaultPath.trim()) : (0, import_obsidian3.normalizePath)("");
    const collectionHierarchy = /* @__PURE__ */ new Map();
    if (collectionsData == null ? void 0 : collectionsData.result) {
      collectionsData.items.forEach((col) => {
        var _a2;
        collectionHierarchy.set(col._id, { title: col.title, parentId: (_a2 = col.parent) == null ? void 0 : _a2.$id });
      });
    }
    let createdCount = 0;
    let skippedCount = 0;
    let errorCount = 0;
    let updatedCount = 0;
    let processed = 0;
    const total = raindrops.length;
    try {
      const raindropsByCollection = {};
      for (const raindrop of raindrops) {
        const collectionId = ((_b = (_a = raindrop.collection) == null ? void 0 : _a.$id) == null ? void 0 : _b.toString()) || "uncategorized";
        if (!raindropsByCollection[collectionId]) {
          raindropsByCollection[collectionId] = [];
        }
        raindropsByCollection[collectionId].push(raindrop);
      }
      for (const [collectionId, collectionRaindrops] of Object.entries(raindropsByCollection)) {
        try {
          for (const raindrop of collectionRaindrops) {
            try {
              const result = await this.processRaindrop(
                raindrop,
                baseTargetFolderPath,
                settingsFMTags,
                options,
                loadingNotice,
                processed,
                total,
                collectionHierarchy,
                collectionIdToNameMap
              );
              if (result.success) {
                if (result.type === "created") createdCount++;
                else if (result.type === "updated") updatedCount++;
                else if (result.type === "skipped") skippedCount++;
              } else {
                errorCount++;
              }
              processed++;
            } catch (error) {
              errorCount++;
              processed++;
              console.error("Error processing raindrop:", error);
            }
          }
        } catch (error) {
          console.error(`Error processing collection ${collectionId}:`, error);
        }
      }
      loadingNotice.hide();
      let summary = `${createdCount} notes created.`;
      if (updatedCount > 0) summary += ` ${updatedCount} updated.`;
      if (skippedCount > 0) summary += ` ${skippedCount} skipped (already exist).`;
      if (errorCount > 0) summary += ` ${errorCount} errors.`;
      new import_obsidian3.Notice(summary, 7e3);
    } catch (error) {
      loadingNotice.hide();
      let errorMsg = "An unknown error occurred";
      if (error instanceof Error) errorMsg = error.message;
      else if (typeof error === "string") errorMsg = error;
      new import_obsidian3.Notice(`Error processing raindrops: ${errorMsg}`, 1e4);
      console.error("Error processing raindrops:", error);
    }
  }
  async processRaindrop(raindrop, baseTargetFolderPath, settingsFMTags, options, loadingNotice, processed, total, collectionHierarchy, collectionIdToNameMap) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    try {
      const { app } = this;
      const escapeYamlStringValue = (str) => {
        if (str === void 0 || str === null) return "";
        return str.replace(/"/g, '\\"');
      };
      const generatedFilename = this.generateFileName(raindrop, options.useRaindropTitleForFileName);
      let individualNoteTargetFolderPath = baseTargetFolderPath;
      if ((_a = raindrop.collection) == null ? void 0 : _a.$id) {
        const pathSegments = this.getFullPathSegments(raindrop.collection.$id, collectionHierarchy, collectionIdToNameMap);
        if (pathSegments.length > 0) {
          const collectionSubPath = pathSegments.join("/");
          individualNoteTargetFolderPath = (0, import_obsidian3.normalizePath)(`${baseTargetFolderPath}/${collectionSubPath}`);
        }
      }
      if (individualNoteTargetFolderPath && !await app.vault.adapter.exists(individualNoteTargetFolderPath)) {
        await createFolderStructure(app, individualNoteTargetFolderPath);
      }
      const filePath = (0, import_obsidian3.normalizePath)(`${individualNoteTargetFolderPath}/${generatedFilename}.md`);
      const raindropTitle = raindrop.title || "Untitled";
      loadingNotice.setMessage(`Processing '${raindropTitle}'... (${processed}/${total})`);
      let processOutcome = "created";
      const templateData = {
        id: raindrop._id,
        title: escapeYamlStringValue(raindrop.title),
        excerpt: escapeYamlStringValue(raindrop.excerpt || ""),
        note: escapeYamlStringValue(raindrop.note || ""),
        link: raindrop.link,
        // URLs generally don't need YAML escaping unless they have special chars
        cover: raindrop.cover || "",
        // URLs generally don't need YAML escaping
        created: raindrop.created,
        lastupdate: raindrop.lastUpdate,
        // Changed from lastUpdate
        type: raindrop.type,
        // Flattened collection data
        collectionId: ((_b = raindrop.collection) == null ? void 0 : _b.$id) || 0,
        collectionTitle: escapeYamlStringValue(collectionIdToNameMap.get(((_c = raindrop.collection) == null ? void 0 : _c.$id) || 0) || "Unknown"),
        collectionPath: escapeYamlStringValue(this.getFullPathSegments(((_d = raindrop.collection) == null ? void 0 : _d.$id) || 0, collectionHierarchy, collectionIdToNameMap).join("/")),
        // Add collectionParentId if it exists
        ...collectionHierarchy.has(((_e = raindrop.collection) == null ? void 0 : _e.$id) || 0) && ((_g = collectionHierarchy.get(((_f = raindrop.collection) == null ? void 0 : _f.$id) || 0)) == null ? void 0 : _g.parentId) !== void 0 && {
          collectionParentId: (_i = collectionHierarchy.get(((_h = raindrop.collection) == null ? void 0 : _h.$id) || 0)) == null ? void 0 : _i.parentId
        },
        tags: (raindrop.tags || []).map((tag) => escapeYamlStringValue(tag)),
        highlights: (raindrop.highlights || []).map((h) => ({
          ...h,
          text: escapeYamlStringValue(h.text),
          note: escapeYamlStringValue(h.note)
        })),
        bannerFieldName: this.settings.bannerFieldName,
        // Pre-calculated fields for helpers
        url: raindrop.link || ""
      };
      try {
        const enhancedDataForRender = {
          ...templateData,
          // Spread the original templateData
          url: templateData.link || "",
          // Ensure url is available, aliasing link
          domain: this.getDomain(templateData.link || ""),
          // Pre-calculate values that used helpers in the template:
          renderedType: this.raindropType(templateData.type),
          // Cast type to RaindropType
          formattedCreatedDate: this.formatDate(templateData.created),
          formattedUpdatedDate: this.formatDate(templateData.lastupdate),
          // Changed from lastUpdate
          formattedTags: this.formatTags(templateData.tags || [])
        };
        if (this.settings.isTemplateSystemEnabled) {
          const template = this.getTemplateForType(raindrop.type, options);
          const fileContent = this.renderTemplate(template, enhancedDataForRender);
          await app.vault.create(filePath, fileContent);
          return { success: true, type: processOutcome };
        } else {
          const {
            id,
            title,
            excerpt,
            note,
            link,
            cover,
            created,
            lastUpdate: rdLastUpdate,
            type,
            tags
            // Keep raindrop.lastUpdate as rdLastUpdate for source
          } = raindrop;
          let descriptionYaml = "";
          if (excerpt) {
            if (excerpt.includes("\n")) {
              descriptionYaml = `description: |
${excerpt.split("\n").map((line) => `  ${line}`).join("\n")}`;
            } else {
              descriptionYaml = `description: "${excerpt.replace(/"/g, '"')}"`;
            }
          } else {
            descriptionYaml = `description: ""`;
          }
          let frontmatter = `---
`;
          frontmatter += `id: ${id}
`;
          frontmatter += `title: "${title.replace(/"/g, '"')}"
`;
          frontmatter += `${descriptionYaml}
`;
          frontmatter += `source: ${link}
`;
          frontmatter += `type: ${type}
`;
          frontmatter += `created: ${created}
`;
          frontmatter += `lastupdate: ${rdLastUpdate}
`;
          if (templateData.collectionId) {
            frontmatter += `collectionId: ${templateData.collectionId}
`;
            frontmatter += `collectionTitle: "${escapeYamlStringValue(templateData.collectionTitle)}"
`;
            frontmatter += `collectionPath: "${escapeYamlStringValue(templateData.collectionPath)}"
`;
            if (templateData.collectionParentId) {
              frontmatter += `collectionParentId: ${templateData.collectionParentId}
`;
            }
          }
          frontmatter += `tags:
`;
          const finalTags = (tags || []).map((tag) => `  - ${tag.trim().replace(/ /g, "_").replace(/[#?"*<>:|]/g, "")}`).join("\n");
          frontmatter += `${finalTags}
`;
          if (cover) {
            frontmatter += `${this.settings.bannerFieldName}: ${cover}
`;
          }
          frontmatter += `---

`;
          let noteBody = "";
          const altText = sanitizeFileName(title) || "Cover Image";
          if (cover) {
            noteBody += `![${altText}](${cover})

`;
          }
          noteBody += `# ${title}

`;
          if (excerpt) {
            noteBody += `## Description
${excerpt}

`;
          }
          if (templateData.note) {
            noteBody += `## Notes
${templateData.note}

`;
          }
          if (templateData.highlights && templateData.highlights.length > 0) {
            noteBody += "## Highlights\n";
            templateData.highlights.forEach((highlight) => {
              noteBody += `- ${highlight.text.replace(/\r\n|\r|\n/g, " ")}
`;
              if (highlight.note) {
                noteBody += `  *Note:* ${highlight.note.replace(/\r\n|\r|\n/g, " ")}
`;
              }
            });
            noteBody += "\n";
          }
          const basicContent = frontmatter + noteBody;
          await app.vault.create(filePath, basicContent);
          return { success: true, type: processOutcome };
        }
      } catch (error) {
        const isFileExistsError = error instanceof Error && error.message && error.message.toLowerCase().includes("file already exists");
        if (isFileExistsError) {
          console.warn(`Attempted to create file ${filePath} but it already exists. This was not handled by update/skip logic (e.g., neither 'update existing' nor 'fetch only new' was applicable or led to a skip). File will be skipped. Options: updateExisting=${options.updateExisting}, fetchOnlyNew=${options.fetchOnlyNew}`);
          return { success: true, type: "skipped" };
        }
        console.error(`Error during file operation for ${generatedFilename} at path ${filePath}:`, error);
        return { success: false, type: "skipped" };
      }
    } catch (error) {
      console.error("Unexpected error in processRaindrop for item ID " + raindrop._id + ":", error);
      return { success: false, type: "skipped" };
    }
  }
  getFullPathSegments(collectionId, collectionHierarchy, collectionIdToNameMap) {
    const segments = [];
    let currentId = collectionId;
    while (currentId !== void 0 && currentId !== 0 && currentId !== SystemCollections.UNSORTED && currentId !== SystemCollections.TRASH) {
      const collection = collectionHierarchy.get(currentId);
      if (!collection) break;
      const name = collectionIdToNameMap.get(currentId);
      if (name) {
        segments.unshift(sanitizeFileName(name));
      }
      currentId = collection.parentId;
    }
    return segments;
  }
  // The updateRibbonIcon method is already defined at line ~360
  formatDate(date) {
    try {
      return new Date(date).toLocaleDateString();
    } catch (e) {
      return "";
    }
  }
  formatDateISO(date) {
    try {
      return new Date(date).toISOString();
    } catch (e) {
      return "";
    }
  }
  formatTags(tags) {
    return tags.map((tag) => `#${tag.trim()}`).join(" ");
  }
  getDomain(url) {
    try {
      return new URL(url).hostname;
    } catch (e) {
      return "";
    }
  }
  raindropType(type) {
    const types = {
      link: "Web Link",
      article: "Article",
      image: "Image",
      video: "Video",
      document: "Document",
      audio: "Audio"
    };
    return types[type] || type;
  }
  renderTemplate(template, data) {
    const enhancedData = {
      ...data,
      url: data.link || "",
      domain: this.getDomain(data.link || ""),
      formatDate: (date) => this.formatDate(date),
      formatDateISO: (date) => this.formatDateISO(date),
      formatTags: (tags) => this.formatTags(tags),
      raindropType: (type) => this.raindropType(type),
      updated: data.lastupdate || ""
      // Changed from lastUpdate
    };
    return template.replace(/{{#if ([^}]+)}}([\s\S]*?)(?:{{else}}([\s\S]*?))?{{\/if}}/g, (match, conditionVar, content, elseContent) => {
      const value = this.getNestedProperty(enhancedData, conditionVar.trim());
      if (value && (Array.isArray(value) ? value.length > 0 : !!value)) {
        return content;
      }
      return elseContent || "";
    }).replace(/{{#each ([^}]+)}}([\s\S]*?){{\/each}}/g, (match, arrayVar, content) => {
      const array = this.getNestedProperty(enhancedData, arrayVar.trim());
      if (!Array.isArray(array)) return "";
      return array.map((item) => {
        let itemContent = content.replace(/{{this}}/g, String(item));
        return itemContent.replace(/{{([^}]+)}}/g, (m, key) => {
          if (key.includes(".")) {
            return String(this.getNestedProperty(item, key) || "");
          }
          return String(item[key] || "");
        });
      }).join("");
    }).replace(/{{([^}]+)}}/g, (match, key) => {
      const value = this.getNestedProperty(enhancedData, key.trim());
      if (typeof value === "object" && value !== null) {
        return this.formatYamlValue(value);
      }
      return String(value || "");
    });
  }
  formatYamlValue(value, indentLevel = 0) {
    const indent = "  ".repeat(indentLevel);
    if (value === null || value === void 0) {
      return "null";
    }
    if (typeof value === "boolean") {
      return value ? "true" : "false";
    }
    if (typeof value === "number") {
      return value.toString();
    }
    if (typeof value === "string") {
      if (value.includes("\n") || value.includes(":") || value.includes("{") || value.includes("}") || value.includes("[") || value.includes("]") || value.includes("#") || value.includes("*") || value.includes("&") || value.includes("!") || value.includes("|") || value.includes(">") || value.includes("`") || value.trim() === "" || /^[0-9]/.test(value) || /^true$|^false$|^yes$|^no$|^on$|^off$/i.test(value)) {
        if (value.includes("\n")) {
          return "|\n" + value.split("\n").map((line) => `${indent}  ${line}`).join("\n");
        }
        return `"${value.replace(/"/g, '\\"')}"`;
      }
      return value;
    }
    if (Array.isArray(value)) {
      if (value.length === 0) {
        return "[]";
      }
      return value.map((item) => `
${indent}- ${this.formatYamlValue(item, indentLevel + 1)}`).join("");
    }
    if (typeof value === "object") {
      const entries = Object.entries(value);
      if (entries.length === 0) {
        return "{}";
      }
      const keysIndent = "  ".repeat(indentLevel + 1);
      return entries.map(([key, val]) => {
        const formattedValue = this.formatYamlValue(val, indentLevel + 1);
        if (formattedValue.startsWith("\\n")) {
          return `\\n${keysIndent}${key}:${formattedValue}`;
        } else {
          return `\\n${keysIndent}${key}: ${formattedValue}`;
        }
      }).join("");
    }
    return String(value);
  }
  escapeYamlString(str) {
    return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\t/g, "\\t").replace(/\r/g, "\\r");
  }
  getNestedProperty(obj, path) {
    return path.split(".").reduce((current, prop) => {
      return current && current[prop] !== void 0 ? current[prop] : void 0;
    }, obj);
  }
  // New method to fetch all user collections
  async fetchAllUserCollections() {
    var _a, _b;
    if (!this.settings.apiToken) {
      console.warn("API token not set. Cannot fetch user collections.");
      new import_obsidian3.Notice("API token not set. Cannot fetch collections for modal.", 5e3);
      return [];
    }
    const baseApiUrl = "https://api.raindrop.io/rest/v1";
    const fetchOptions = {
      method: "GET",
      headers: {
        "Authorization": `Bearer ${this.settings.apiToken}`
      }
    };
    let allCollections = [];
    try {
      const rootResponse = await fetchWithRetry(
        this.app,
        `${baseApiUrl}/collections`,
        fetchOptions,
        this.rateLimiter
      );
      const rootData = rootResponse;
      if ((rootData == null ? void 0 : rootData.result) && (rootData == null ? void 0 : rootData.items)) {
        allCollections = allCollections.concat(rootData.items);
      } else if (!(rootData == null ? void 0 : rootData.result)) {
        console.warn("Failed to fetch root collections or result was false:", rootData);
      }
      const nestedResponse = await fetchWithRetry(
        this.app,
        `${baseApiUrl}/collections/childrens`,
        fetchOptions,
        this.rateLimiter
      );
      const nestedData = nestedResponse;
      if ((nestedData == null ? void 0 : nestedData.result) && (nestedData == null ? void 0 : nestedData.items)) {
        allCollections = allCollections.concat(nestedData.items);
      } else if (!(nestedData == null ? void 0 : nestedData.result)) {
        console.warn("Failed to fetch nested collections or result was false:", nestedData);
      }
      const uniqueCollections = Array.from(new Map(allCollections.map((col) => [col._id, col])).values()).filter((col) => col._id !== SystemCollections.TRASH && col._id !== SystemCollections.UNSORTED);
      if (allCollections.length > 0 && uniqueCollections.length === 0 && (((_a = rootData == null ? void 0 : rootData.items) == null ? void 0 : _a.length) || ((_b = nestedData == null ? void 0 : nestedData.items) == null ? void 0 : _b.length))) {
        console.log("Only system collections (Trash/Unsorted) were found.");
      } else if (allCollections.length === 0) {
        console.warn("No collections were fetched from either endpoint.");
      }
      return uniqueCollections;
    } catch (error) {
      console.error("Error fetching all user collections for modal:", error);
      new import_obsidian3.Notice("Failed to load your Raindrop.io collections for selection.", 7e3);
      return [];
    }
  }
  // Method to fetch and process a single Raindrop item
  async fetchSingleRaindrop(itemId, vaultPath, appendTags) {
    var _a;
    if (!this.settings.apiToken) {
      new import_obsidian3.Notice("Please configure your Raindrop.io API token in the plugin settings.", 1e4);
      return;
    }
    if (!itemId) {
      new import_obsidian3.Notice("Invalid Item ID provided for Quick Import.", 5e3);
      return;
    }
    const loadingNotice = new import_obsidian3.Notice(`Fetching Raindrop item ID: ${itemId}...`, 0);
    const baseApiUrl = "https://api.raindrop.io/rest/v1";
    const fetchOptions = {
      method: "GET",
      headers: { "Authorization": `Bearer ${this.settings.apiToken}` }
    };
    try {
      const response = await fetchWithRetry(
        this.app,
        `${baseApiUrl}/raindrop/${itemId}`,
        fetchOptions,
        this.rateLimiter
      );
      const data = response;
      let raindropItem;
      if (data.result && data.item) {
        raindropItem = data.item;
      } else if (data.result && data.items && data.items.length > 0) {
        raindropItem = data.items[0];
        console.warn(`Single raindrop fetch for ID ${itemId} returned an items array. Using the first item.`);
      }
      if (!raindropItem) {
        loadingNotice.hide();
        const errorMsg = data.result === false ? data.errorMessage || "API indicated failure." : "Item not found or invalid response.";
        new import_obsidian3.Notice(`Failed to fetch Raindrop item ${itemId}: ${errorMsg}`, 7e3);
        console.error(`Failed to fetch Raindrop item ${itemId}:`, data);
        return;
      }
      const singleItemOptions = {
        vaultPath,
        // User-specified or plugin default
        collections: "",
        // Not applicable for single item by ID
        apiFilterTags: "",
        // Not applicable
        includeSubcollections: false,
        // Not applicable
        appendTagsToNotes: appendTags || "",
        // User-specified for quick import
        useRaindropTitleForFileName: this.settings.fileNameTemplate !== "{{id}}",
        // Infer from settings
        tagMatchType: "all",
        // Default, not critical here
        filterType: "all",
        // Default, not critical here
        fetchOnlyNew: false,
        // For quick import, typically we want to create or update
        updateExisting: true,
        // Default to true for quick import to allow updates
        useDefaultTemplate: false,
        // Respect template settings
        overrideTemplates: false
        // Respect template settings
      };
      let collectionsData = void 0;
      let collectionIdToNameMap = /* @__PURE__ */ new Map();
      if ((_a = raindropItem.collection) == null ? void 0 : _a.$id) {
        loadingNotice.setMessage(`Fetching collection info for item ${itemId}...`);
        const allUserCollections = await this.fetchAllUserCollections();
        if (allUserCollections.length > 0) {
          collectionsData = { result: true, items: allUserCollections };
          allUserCollections.forEach((col) => collectionIdToNameMap.set(col._id, col.title));
        }
      }
      await this.processRaindrops(
        [raindropItem],
        singleItemOptions.vaultPath,
        singleItemOptions.appendTagsToNotes,
        singleItemOptions.useRaindropTitleForFileName,
        loadingNotice,
        // Pass the notice
        singleItemOptions,
        collectionsData,
        // Pass fetched collections data for path context
        [],
        // resolvedCollectionIds not directly applicable
        collectionIdToNameMap
        // Pass map for titles
      );
    } catch (error) {
      loadingNotice.hide();
      let errorMessage = "An unknown error occurred during quick import";
      if (error instanceof Error) errorMessage = error.message;
      new import_obsidian3.Notice(`Error during Quick Import of item ${itemId}: ${errorMessage}`, 1e4);
      console.error(`Error quick importing Raindrop ID ${itemId}:`, error);
    }
  }
};
var RaindropToObsidianSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Make It Rain Settings" });
    containerEl.createEl("h2", { text: "\u{1F4A7} Raindrop.io API Configuration" });
    const apiTokenSetting = new import_obsidian3.Setting(containerEl).setName("Raindrop.io API Token").setDesc('Create a "Test Token" from your Raindrop.io Apps settings.').addText((text) => {
      text.setPlaceholder("Enter your API token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
    }).addButton((button) => {
      button.setButtonText("Verify Token").setIcon("checkmark").setCta().onClick(async () => {
        await this.verifyApiToken();
      });
    });
    const apiTokenHelpLink = apiTokenSetting.nameEl.createEl("a", {
      href: "https://frostmute.github.io/make-it-rain/configuration#api-token",
      text: " (?)",
      cls: "make-it-rain-help-link",
      title: "How to get your API Token"
    });
    apiTokenHelpLink.setAttr("target", "_blank");
    containerEl.createEl("h2", { text: "\u2699\uFE0F General Import Settings" });
    new import_obsidian3.Setting(containerEl).setName("Default Vault Save Location").setDesc("Specify the default folder for imported notes (e.g., Imports/Raindrops). Leave blank for vault root.").addText((text) => {
      text.setPlaceholder("e.g., Raindrops/").setValue(this.plugin.settings.defaultFolder).onChange(async (value) => {
        this.plugin.settings.defaultFolder = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
    });
    const fileNameTemplateSetting = new import_obsidian3.Setting(containerEl).setName("Filename Template").setDesc('Define the filename for notes when "Use Raindrop Title" is enabled. Placeholders: {{title}}, {{id}}, {{collectionTitle}}, {{date}} (YYYY-MM-DD).').addText((text) => {
      text.setPlaceholder("{{title}}").setValue(this.plugin.settings.fileNameTemplate).onChange(async (value) => {
        this.plugin.settings.fileNameTemplate = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
    });
    const fileNameTemplateHelpLink = fileNameTemplateSetting.nameEl.createEl("a", {
      href: "https://frostmute.github.io/make-it-rain/configuration#filename-template",
      text: " (?)",
      cls: "make-it-rain-help-link",
      title: "Documentation for Filename Template"
    });
    fileNameTemplateHelpLink.setAttr("target", "_blank");
    new import_obsidian3.Setting(containerEl).setName("Banner Frontmatter Field Name").setDesc("Customize the frontmatter field name for the banner/cover image (default: banner).").addText((text) => {
      text.setPlaceholder("banner").setValue(this.plugin.settings.bannerFieldName).onChange(async (value) => {
        this.plugin.settings.bannerFieldName = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h2", { text: "\u{1F3A8} User Interface" });
    new import_obsidian3.Setting(containerEl).setName("Show Ribbon Icon").setDesc("Toggle the Make It Rain ribbon icon in the Obsidian sidebar.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showRibbonIcon).onChange(async (value) => {
        this.plugin.settings.showRibbonIcon = value;
        await this.plugin.saveSettings();
        this.plugin.updateRibbonIcon();
      });
    });
    containerEl.createEl("hr");
    containerEl.createEl("h2", { text: "\u{1F4C4} Template System" });
    new import_obsidian3.Setting(containerEl).setName("Enable Template System").setDesc("Use custom templates for formatting imported notes. If disabled, a basic note structure will be used.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.isTemplateSystemEnabled).onChange(async (value) => {
        this.plugin.settings.isTemplateSystemEnabled = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.isTemplateSystemEnabled) {
      containerEl.createEl("h3", { text: "Default Template" });
      new import_obsidian3.Setting(containerEl).setDesc("This template is used if no content-type specific template is active or defined below.").setClass("setting-item-stacked").addTextArea((text) => {
        text.setPlaceholder("Enter your default Handlebars template here...").setValue(this.plugin.settings.defaultTemplate).onChange(async (value) => {
          this.plugin.settings.defaultTemplate = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.rows = 15;
        text.inputEl.style.width = "100%";
        text.inputEl.style.fontFamily = "monospace";
      }).addButton((button) => {
        button.setButtonText("Reset to Default").setIcon("undo").setTooltip("Reset this template to its original default value").onClick(async () => {
          this.plugin.settings.defaultTemplate = DEFAULT_SETTINGS.defaultTemplate;
          await this.plugin.saveSettings();
          this.display();
          new import_obsidian3.Notice("Default template has been reset.");
        });
      });
      containerEl.createEl("h3", { text: "Content-Type Specific Templates" });
      const contentTypeDesc = containerEl.createEl("p", { cls: "setting-item-description" });
      contentTypeDesc.innerHTML = 'Define specific templates for different Raindrop types. If a type-specific template is enabled and filled, it will be used instead of the default template. If disabled or empty, the default template is used for that type. Visit the <a href="https://frostmute.github.io/make-it-rain/template-system/">documentation</a> for available variables.';
      const contentTypes = Object.values(RaindropTypes);
      for (const type of contentTypes) {
        const typeKey = type;
        containerEl.createEl("h4", { text: `${type.charAt(0).toUpperCase() + type.slice(1)} Template` });
        new import_obsidian3.Setting(containerEl).setName(`Enable ${type} Template`).setDesc(`Use a custom template for "${type}" items.`).addToggle((toggle) => {
          toggle.setValue(this.plugin.settings.contentTypeTemplateToggles[typeKey]).onChange(async (value) => {
            this.plugin.settings.contentTypeTemplateToggles[typeKey] = value;
            await this.plugin.saveSettings();
            this.display();
          });
        });
        if (this.plugin.settings.contentTypeTemplateToggles[typeKey]) {
          new import_obsidian3.Setting(containerEl).setDesc(`Template for "${type}" content. Leave empty to use the default template.`).setClass("setting-item-stacked").addTextArea((text) => {
            text.setPlaceholder(`Enter template for ${type} items...`).setValue(this.plugin.settings.contentTypeTemplates[typeKey]).onChange(async (value) => {
              this.plugin.settings.contentTypeTemplates[typeKey] = value;
              await this.plugin.saveSettings();
            });
            text.inputEl.rows = 10;
            text.inputEl.style.width = "100%";
            text.inputEl.style.fontFamily = "monospace";
          }).addButton((button) => {
            button.setButtonText("Reset").setIcon("undo").setTooltip(`Reset ${type} template to its original default`).onClick(async () => {
              if (DEFAULT_SETTINGS.contentTypeTemplates[typeKey]) {
                this.plugin.settings.contentTypeTemplates[typeKey] = DEFAULT_SETTINGS.contentTypeTemplates[typeKey];
                await this.plugin.saveSettings();
                this.display();
                new import_obsidian3.Notice(`${type.charAt(0).toUpperCase() + type.slice(1)} template has been reset.`);
              } else {
                new import_obsidian3.Notice(`Error: Default template for ${type} not found.`, 7e3);
              }
            });
          });
        }
        containerEl.createEl("hr");
      }
    }
    containerEl.createEl("hr");
    const footer = containerEl.createDiv({ cls: "setting-footer" });
    footer.innerHTML = `
            <p><strong>Make It Rain v${this.plugin.manifest.version}</strong></p>
            <p>Developed by <a href="https://github.com/frostmute" target="_blank">frostmute (Jonathan Wagner)</a>.</p>
            <p>Found this plugin helpful? Consider <a href="https://ko-fi.com/frostmute" target="_blank">supporting its development</a>.</p>
            <p>For help, feature requests, or to report issues, please visit the <a href="https://github.com/frostmute/make-it-rain/issues" target="_blank">GitHub repository</a>.</p>
        `;
  }
  async verifyApiToken() {
    const { apiToken } = this.plugin.settings;
    if (!apiToken) {
      new import_obsidian3.Notice("Please enter an API token first.", 5e3);
      return;
    }
    new import_obsidian3.Notice("Verifying API token...", 3e3);
    const baseApiUrl = "https://api.raindrop.io/rest/v1";
    const fetchOptions = {
      headers: {
        "Authorization": `Bearer ${apiToken}`,
        "Content-Type": "application/json"
      }
    };
    try {
      const response = await (0, import_obsidian4.request)({
        url: `${baseApiUrl}/user`,
        method: "GET",
        headers: fetchOptions.headers
      });
      let data;
      if (typeof response === "string") {
        data = JSON.parse(response);
      } else {
        data = response;
      }
      if (data.result) {
        new import_obsidian3.Notice("API Token is valid!", 5e3);
      } else {
        const errorMessage = data.message || data.error || "Invalid API token or connection issue.";
        new import_obsidian3.Notice(`API Token verification failed: ${errorMessage}`, 1e4);
        console.error("API Token verification failed:", data);
      }
    } catch (error) {
      let errorMsg = "An error occurred during token verification.";
      if (error instanceof Error) errorMsg = error.message;
      else if (typeof error === "string") errorMsg = error;
      new import_obsidian3.Notice(`API Token verification failed: ${errorMsg}`, 1e4);
      console.error("Error verifying API token:", error);
    }
  }
};
